version: "3"
services:

  defilecture_db:
    image: mariadb:latest
    container_name: defilecture_db
    networks:
      defilecturenet:
        ipv4_address: 172.21.0.2
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: America/New_York
    restart: on-failure

  defilecture:
    build:
      context: docker/
      dockerfile: defilecture.df
    container_name: defilecture
    networks:
      defilecturenet:
        ipv4_address: 172.21.0.3
    volumes:
      - "./build/defilecture/:/usr/local/tomcat/webapps/ROOT/"
    restart: on-failure
    environment:
      TZ: America/New_York
    depends_on:
      - defilecture_db

networks:
  defilecturenet:
    ipam:
      config:
        - subnet: 172.21.0.0/24
