version: "3"
services:

  defilecture_build:
    build:
      context: docker/
      dockerfile: build.df
    volumes:
      - "./DefiLecture-JC:/tmp/src/"

  defilecture_db:
    image: mariadb:latest
    container_name: defilecture_db
    networks:
      defilecturenet:
        ipv4_address: 172.21.0.2
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: on-failure

  defilecture:
    image: tomcat:latest
    container_name: defilecture
    networks:
      defilecturenet:
        ipv4_address: 172.21.0.3
    volumes:
      - "./DefiLecture-JC/build/web/:/usr/local/tomcat/webapps/ROOT/"
    restart: on-failure
    depends_on:
      - defilecture_db

networks:
  defilecturenet:
    ipam:
      config:
        - subnet: 172.21.0.0/24
