ALTER TABLE `compte` 
CHANGE `PRENOM` `PRENOM` VARCHAR(255) 
CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
CHANGE `NOM` `NOM` VARCHAR(255) 
CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
CHANGE `MOT_PASSE` `MOT_PASSE` VARCHAR(12) 
CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
CHANGE `PROGRAMME_ETUDE` `PROGRAMME_ETUDE` VARCHAR(255) 
CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
CHANGE `AVATAR` `AVATAR` VARCHAR(255) 
CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL, 
CHANGE `PSEUDONYME` `PSEUDONYME` VARCHAR(255) 
CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;